name: Build and Release

on:
  push:
    branches:
      - release  # Dedicated branch for release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Zip the files
      run: zip -jr CloseTabButton.xpi src/

    - name: Get Git tag
      id: git_tag
      run: echo "::set-output name=TAG_NAME::$(git describe --tags --abbrev=0)"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.git_tag.outputs.TAG_NAME }}
        release_name: Release ${{ steps.git_tag.outputs.TAG_NAME }}
        body: |
          Changes in this release:
          - Describe your changes here
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CloseTabButton.xpi
        asset_name: CloseTabButton.xpi
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}

